exclude: '^migrations/'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
        name: Fix end of file
      - id: trailing-whitespace
        name: Fix trailing whitespace
      - id: debug-statements
        name: Search for debug statements
      - id: check-merge-conflict
        name: Search merge conflict leftovers
      - id: requirements-txt-fixer
        name: Fix requirements.txt
        args: [requirements.txt, requirements-dev.txt, requirements-test.txt]
      - id: mixed-line-ending
        name: Fix mixed line endings
        args: [--fix=lf]
      - id: fix-encoding-pragma
        name: Fix encoding pragma
        args: [--remove]
      - id: fix-byte-order-marker
        name: Fix byte order marker
  - repo: https://github.com/IamTheFij/docker-pre-commit
    rev: v2.0.0
    hooks:
      - id: hadolint
  - repo: https://github.com/psf/black
    rev: 22.8.0
    hooks:
      - id: black
        name: Black
  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        name: DocStyle
        additional_dependencies: [toml]
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: Reorder python imports
  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        name: Flake8
        additional_dependencies: [flake8-cognitive-complexity, Flake8-pyproject, flake8-bugbear]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        name: Python security
        additional_dependencies: [toml]
        args: [--configfile=pyproject.toml]
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.0
    hooks:
      - id: python-safety-dependencies-check
        name: Dependencies security
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.982
    hooks:
      - id: mypy
        name: Python typing
  - repo: local
    hooks:
      - id: pytest
        name: Tests
        entry: poetry run pytest tests
        language: system
        pass_filenames: false
        stages: [push]
      - id: check-poetry
        name: Poetry check
        description: Validates the structure of the pyproject.toml file
        entry: poetry check
        language: system
        pass_filenames: false
        files: pyproject.toml
